import "./globals.css"; 
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { AuthProvider } from "@/context/AuthContext";
export const metadata = {
  title: "Vege",
  description: "Generated by Sanket Ade",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
     
//       <body>
//         <Navbar/>
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <Navbar/>
        {/* The 'main' tag ensures content takes up space */}
        <main style={{ minHeight: '80vh' }}>
          {children} 
        </main>
        <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}